### ISSUE TITLE
css main naming convention

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/css-validation-fixes#1]
@thomasjbradley 
I'm trying to fix the naming convention for the css folder but on Githubs website I cant seem to figure out how to edit the name. I changed the folder name in my Finder and pulled it in the app but keep getting the same error. So I'm not really sure what to try next.

Sheri

**Comment by thomasjbradley** [comment]
Can you upload a screenshot of what your folders in Finder look like?

**Comment by sheri-thomson** [comment]
<img width="1680" alt="screen shot 2017-10-06 at 9 53 08 pm" src="https://user-images.githubusercontent.com/31968878/31303773-fb08cba2-aae0-11e7-87cb-81d6349c427f.png">

**Comment by sheri-thomson** [comment]
<img width="1680" alt="screen shot 2017-10-06 at 9 57 15 pm" src="https://user-images.githubusercontent.com/31968878/31303787-6951f39a-aae1-11e7-9d80-d8fa6e584f80.png">

**Comment by thomasjbradley** [comment]
Look really, really closely at this filename:

![filename](https://user-images.githubusercontent.com/105192/31303808-f42e365e-aae1-11e7-9990-16aa993fd66f.jpg)

Then double check in Finder.

**Comment by sheri-thomson** [comment]
Thank you :)
